```{r}
#| label: kmfunc
#| cache: true
#| cache.comments: false
#| dependson: outcomesfunc

end_followup <- 10

kmfunc <- function(efcat, sexcat = c("Female", "Male"), time, event, eventname, coxest = outall, km = F) {
  levs <- levels(rsdata %>% pull(shf_primaryetiology_cat))
  nlevs <- length(levs)

  cox_crude <- c(
    "Crude HR (95% CI)",
    gsub("\\,.*", "", coxest %>% filter(EF == efcat & Outcome == outvars$name[nr]) %>% pull(hrcicrude))
  )

  cox_adj <- c(
    "Adjusted HR (95% CI)",
    gsub("\\,.*", "", coxest %>% filter(EF == efcat & Outcome == outvars$name[nr]) %>% pull(hrciadj))
  )

  fit <- survfit(formula(paste0("Surv(", time, ",", event, "== 'Yes') ~ shf_primaryetiology_cat")),
    data = rsdata %>% filter(shf_ef_cat == efcat & shf_sex %in% sexcat),
  )

  s <- summary(fit, times = seq(0, end_followup * 365.25, 1), extend = T)

  if (km) {
    est <- s$surv
  } else {
    est <- 1 - s$surv
  }

  plot_data <- tibble(
    "time" = s$time,
    "n.risk" = s$n.risk,
    "n.event" = s$n.event,
    "n.censor" = s$n.censor,
    "estimate" = est,
    # "estimate" = s$surv,
    "strata" = s$strata
  ) %>%
    mutate(
      strata = fct_rev(fct_inorder(str_remove_all(strata, "shf_primaryetiology_cat="))),
    )
  addon <- 0.3
  ylim <- c(0, 1 + addon)
  ylab <- paste0(eventname, " (%)")
  addonx <- ifelse(km, 2.2, 0)

  p <- ggplot(plot_data, aes(x = time / 365, y = estimate, color = strata)) +
    geom_step(aes(linetype = strata), linewidth = 1) +
    scale_color_manual(values = c(global_cols[4:1])) +
    # scale_x_continuous(breaks = seq(0, endfollow, 1), limits = c(0, endfollow), expand = c(0, 0)) +
    # scale_y_continuous(labels = scales::label_percent(suffix = ""), limits = c(0, 1), expand = c(0, 0)) +
    scale_x_continuous(breaks = seq(0, end_followup, 1), limits = c(0, end_followup)) +
    scale_y_continuous(labels = scales::label_percent(suffix = ""), breaks = seq(0, 1, 0.25), limits = ylim) +
    theme_classic() +
    theme(
      text = element_text(size = 20),
      legend.position = "none",
      legend.title = element_blank()
    ) +
    labs(x = "Follow-up (years)", y = ylab) +
    annotate("text",
      x = 0 + addonx, y = c(1, .9, .8, .7, .6) + addon,
      label = c("", levs), hjust = 0, size = 6, colour = c("black", global_cols[1:4])
    ) +
    annotate("text",
      x = 3.2 + addonx, y = c(1, .9, .8, .7, .6) + addon,
      label = cox_crude, hjust = 0.5, size = 6, colour = c("black", global_cols[1:4])
    ) +
    annotate("text",
      x = 6.4 + addonx, y = c(1, .9, .8, .7, .6) + addon,
      label = cox_adj, hjust = 0.5, size = 6, colour = c("black", global_cols[1:4])
    )

  # n at risk
  table_data <- plot_data %>%
    filter(
      time %in% c(seq(0, end_followup, 2) * 365)
    )

  t <- ggplot(table_data, aes(y = strata, x = time / 365)) +
    geom_text(aes(label = n.risk), size = 6, colour = rep(global_cols[1:4], each = 6)) +
    # scale_x_continuous(breaks = seq(0, endfollow, 1), limits = c(0, endfollow), expand = c(0, 0)) +
    # scale_y_discrete(expand = c(0, 0)) +
    scale_x_continuous(breaks = seq(0, end_followup, 2), limits = c(0, end_followup)) +
    coord_cartesian(xlim = c(0, end_followup), clip = "off") +
    labs(subtitle = "No. at risk") +
    theme(
      plot.caption = element_text(size = 20),
      panel.background = element_blank(),
      text = element_text(size = 20),
      axis.text.x = element_blank(),
      axis.ticks = element_blank(),
      axis.title = element_blank(),
      # plot.margin = unit(c(0, 1, 0, 3), "cm"), # trouble
      # axis.text.y = element_blank()
      # axis.text.y = element_text(margin = margin(0, 0, 0, 100))
      axis.text.y = element_text(hjust = 0, colour = global_cols[4:1])
    )

  km <- (p / t) + plot_layout(height = c(1, .25))
  if (output) {
    create_pptx(km)
  }
  km
}
```

```{r}
#| label: fig-cic-pef
#| cache: true
#| cache.comments: false
#| dependson: kmfunc
#| fig-cap: "Cumulative incidence - HFpEF"
#| fig-subcap: !expr outvars$name
#| layout-ncol: 2
#| layout-nrow: 2

nr <- 1
kmfunc(
  efcat = "HFpEF",
  time = outvars$time[nr],
  event = outvars$var[nr],
  eventname = outvars$shortname[nr],
  km = T
)
nr <- 2
kmfunc(
  efcat = "HFpEF",
  time = outvars$time[nr],
  event = outvars$var[nr],
  eventname = outvars$shortname[nr],
  km = T
)
nr <- 3
kmfunc(
  efcat = "HFpEF",
  time = outvars$time[nr],
  event = outvars$var[nr],
  eventname = outvars$shortname[nr]
)
```

```{r}
#| label: fig-cic-mref
#| cache: true
#| cache.comments: false
#| dependson: kmfunc
#| fig-cap: "Cumulative incidence - HFmrEF"
#| fig-subcap: !expr outvars$name
#| layout-ncol: 2
#| layout-nrow: 2

nr <- 1
kmfunc(
  efcat = "HFmrEF",
  time = outvars$time[nr],
  event = outvars$var[nr],
  eventname = outvars$shortname[nr],
  km = T
)
nr <- 2
kmfunc(
  efcat = "HFmrEF",
  time = outvars$time[nr],
  event = outvars$var[nr],
  eventname = outvars$shortname[nr],
  km = T
)
nr <- 3
kmfunc(
  efcat = "HFmrEF",
  time = outvars$time[nr],
  event = outvars$var[nr],
  eventname = outvars$shortname[nr]
)
```

```{r}
#| label: fig-cic-ref
#| cache: true
#| cache.comments: false
#| dependson: kmfunc
#| fig-cap: "Cumulative incidence - HFrEF"
#| fig-subcap: !expr outvars$name
#| layout-ncol: 2
#| layout-nrow: 2

nr <- 1
kmfunc(
  efcat = "HFrEF",
  time = outvars$time[nr],
  event = outvars$var[nr],
  eventname = outvars$shortname[nr],
  km = T
)
nr <- 2
kmfunc(
  efcat = "HFrEF",
  time = outvars$time[nr],
  event = outvars$var[nr],
  eventname = outvars$shortname[nr],
  km = T
)
nr <- 3
kmfunc(
  efcat = "HFrEF",
  time = outvars$time[nr],
  event = outvars$var[nr],
  eventname = outvars$shortname[nr]
)
```

```{r}
#| label: fig-cic-pef-female
#| cache: true
#| cache.comments: false
#| dependson: kmfunc
#| fig-cap: "Cumulative incidence - HFpEF - Female"
#| fig-subcap: !expr outvars$name
#| layout-ncol: 2
#| layout-nrow: 2

nr <- 1
kmfunc(
  efcat = "HFpEF",
  sexcat = "Female",
  time = outvars$time[nr],
  event = outvars$var[nr],
  eventname = outvars$shortname[nr],
  coxest = outall_female,
  km = T
)
nr <- 2
kmfunc(
  efcat = "HFpEF",
  sexcat = "Female",
  time = outvars$time[nr],
  event = outvars$var[nr],
  eventname = outvars$shortname[nr],
  coxest = outall_female,
  km = T
)
nr <- 3
kmfunc(
  efcat = "HFpEF",
  sexcat = "Female",
  time = outvars$time[nr],
  event = outvars$var[nr],
  eventname = outvars$shortname[nr],
  coxest = outall_female
)
```

```{r}
#| label: fig-cic-mref-female
#| cache: true
#| cache.comments: false
#| dependson: kmfunc
#| fig-cap: "Cumulative incidence - HFmrEF - Female"
#| fig-subcap: !expr outvars$name
#| layout-ncol: 2
#| layout-nrow: 2

nr <- 1
kmfunc(
  efcat = "HFmrEF",
  sexcat = "Female",
  time = outvars$time[nr],
  event = outvars$var[nr],
  eventname = outvars$shortname[nr],
  coxest = outall_female,
  km = T
)
nr <- 2
kmfunc(
  efcat = "HFmrEF",
  sexcat = "Female",
  time = outvars$time[nr],
  event = outvars$var[nr],
  eventname = outvars$shortname[nr],
  coxest = outall_female,
  km = T
)
nr <- 3
kmfunc(
  efcat = "HFmrEF",
  sexcat = "Female",
  time = outvars$time[nr],
  event = outvars$var[nr],
  eventname = outvars$shortname[nr],
  coxest = outall_female
)
```

```{r}
#| label: fig-cic-ref-female
#| cache: true
#| cache.comments: false
#| dependson: kmfunc
#| fig-cap: "Cumulative incidence - HFrEF - Female"
#| fig-subcap: !expr outvars$name
#| layout-ncol: 2
#| layout-nrow: 2

nr <- 1
kmfunc(
  efcat = "HFrEF",
  sexcat = "Female",
  time = outvars$time[nr],
  event = outvars$var[nr],
  eventname = outvars$shortname[nr],
  coxest = outall_female,
  km = T
)
nr <- 2
kmfunc(
  efcat = "HFrEF",
  sexcat = "Female",
  time = outvars$time[nr],
  event = outvars$var[nr],
  eventname = outvars$shortname[nr],
  coxest = outall_female,
  km = T
)
nr <- 3
kmfunc(
  efcat = "HFrEF",
  sexcat = "Female",
  time = outvars$time[nr],
  event = outvars$var[nr],
  eventname = outvars$shortname[nr],
  coxest = outall_female
)
```

```{r}
#| label: fig-cic-pef-male
#| cache: true
#| cache.comments: false
#| dependson: kmfunc
#| fig-cap: "Cumulative incidence - HFpEF - Male"
#| fig-subcap: !expr outvars$name
#| layout-ncol: 2
#| layout-nrow: 2

nr <- 1
kmfunc(
  efcat = "HFpEF",
  sexcat = "Male",
  time = outvars$time[nr],
  event = outvars$var[nr],
  eventname = outvars$shortname[nr],
  coxest = outall_male,
  km = T
)
nr <- 2
kmfunc(
  efcat = "HFpEF",
  sexcat = "Male",
  time = outvars$time[nr],
  event = outvars$var[nr],
  eventname = outvars$shortname[nr],
  coxest = outall_male,
  km = T
)
nr <- 3
kmfunc(
  efcat = "HFpEF",
  sexcat = "Male",
  time = outvars$time[nr],
  event = outvars$var[nr],
  eventname = outvars$shortname[nr],
  coxest = outall_male
)
```

```{r}
#| label: fig-cic-mref-male
#| cache: true
#| cache.comments: false
#| dependson: kmfunc
#| fig-cap: "Cumulative incidence - HFmrEF - Male"
#| fig-subcap: !expr outvars$name
#| layout-ncol: 2
#| layout-nrow: 2

nr <- 1
kmfunc(
  efcat = "HFmrEF",
  sexcat = "Male",
  time = outvars$time[nr],
  event = outvars$var[nr],
  eventname = outvars$shortname[nr],
  coxest = outall_male,
  km = T
)
nr <- 2
kmfunc(
  efcat = "HFmrEF",
  sexcat = "Male",
  time = outvars$time[nr],
  event = outvars$var[nr],
  eventname = outvars$shortname[nr],
  coxest = outall_male,
  km = T
)
nr <- 3
kmfunc(
  efcat = "HFmrEF",
  sexcat = "Male",
  time = outvars$time[nr],
  event = outvars$var[nr],
  eventname = outvars$shortname[nr],
  coxest = outall_male
)
```

```{r}
#| label: fig-cic-ref-male
#| cache: true
#| cache.comments: false
#| dependson: kmfunc
#| fig-cap: "Cumulative incidence - HFrEF - Male"
#| fig-subcap: !expr outvars$name
#| layout-ncol: 2
#| layout-nrow: 2

nr <- 1
kmfunc(
  efcat = "HFrEF",
  sexcat = "Male",
  time = outvars$time[nr],
  event = outvars$var[nr],
  eventname = outvars$shortname[nr],
  coxest = outall_male,
  km = T
)
nr <- 2
kmfunc(
  efcat = "HFrEF",
  sexcat = "Male",
  time = outvars$time[nr],
  event = outvars$var[nr],
  eventname = outvars$shortname[nr],
  coxest = outall_male,
  km = T
)
nr <- 3
kmfunc(
  efcat = "HFrEF",
  sexcat = "Male",
  time = outvars$time[nr],
  event = outvars$var[nr],
  eventname = outvars$shortname[nr],
  coxest = outall_male
)
```
