```{r}
#| label: doughnutfunc
#| cache: true
#| cache.comments: false

doughnutfunc <- function(data) {
  lvl0 <- tibble(name = "", n = 0, level = 0, fill = NA, lab = NA)

  lvl1 <- data %>%
    count(shf_ef_cat) %>%
    mutate(
      p = n / sum(n) * 100,
      lab = paste0(shf_ef_cat, "\n", fn(p, 0), "%")
    ) %>%
    mutate(
      level = 1,
      fill = shf_ef_cat
    ) %>%
    rename(name = shf_ef_cat)

  lvl2 <- data %>%
    group_by(shf_ef_cat) %>%
    count(shf_primaryetiology_cat) %>%
    mutate(
      p = n / sum(n) * 100,
      lab = paste0(shf_primaryetiology_cat, "\n", fn(p, 0), "%")
    ) %>%
    ungroup() %>%
    mutate(
      level = 2,
      fill = shf_ef_cat
    ) %>%
    rename(name = shf_primaryetiology_cat)

  piedata <- bind_rows(lvl0, lvl1, lvl2) %>%
    mutate(
      level = as.factor(level),
      name = forcats::fct_inorder(name)
    )

  p <- piedata %>%
    ggplot(aes(x = level, y = n, fill = fill, alpha = level)) +
    geom_col(width = 1, color = "white", position = position_stack()) +
    geom_text(aes(label = lab), size = 4, position = position_stack(vjust = 0.5)) +
    coord_polar(theta = "y") +
    scale_alpha_manual(values = c("0" = 0, "1" = 1, "2" = 0.7)) +
    scale_x_discrete(breaks = NULL) +
    scale_y_continuous(breaks = NULL) +
    scale_fill_brewer(palette = "Dark2", na.translate = F) +
    theme_void() +
    theme(
      legend.position = "none"
    )
  create_pptx(p, width = 6, height = 6)
  p
}
```

```{r}
#| label: fig-doughnut
#| cache: true
#| dependson: doughnutfunc
#| cache.comments: false
#| fig-cap: "Primary etiolgy by EF"
#| fig-height: 6
#| fig-width: 6
#| fig-subcap: !expr c("Overall", "Female", "Male")
#| layout-ncol: 2
#| layout-nrow: 2
#|
doughnutfunc(rsdata)
doughnutfunc(rsdata %>% filter(shf_sex == "Female"))
doughnutfunc(rsdata %>% filter(shf_sex == "Male"))
```
